CREATE TABLE t_cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255),
    senha VARCHAR2(255)
);

CREATE TABLE t_dispositivo(
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(255),
    tipo            VARCHAR2(255),
    consumo_medio   number(10, 2),
    data_instalacao DATE,
    cliente_id      NUMBER
);
alter table t_dispositivo add constraint fk_cliente foreign key (cliente_id) references t_cliente;